# Reference
#assembly: /lustre/backup/WUR/ABGC/shared/ABGC_Projects/Turkey_Assembly/HiC_assembly/Mgal6.fa

# Polished assembly - used for second round of polishing
assembly: /lustre/nobackup/WUR/ABGC/moiti001/results/polished_assembly/results/pilon.fasta

# Directory with data to use (for reads and reference)

BAM: /lustre/backup/WUR/ABGC/shared/ABGC_Projects/Turkey_Assembly/realign_pacbio/pb_mapped_Mgal6.sorted.bam

# file with regions to use for variant calling:
# can be created from the BAM file:
    # module load samtools && samtools idxstats <BAM> | cut -f 1 > chr_names.txt
    # remove the line with an asterisk: awk '!/*/' chr_names.txt > temp && mv temp chr_names.txt
REGIONS: /lustre/nobackup/WUR/ABGC/moiti001/polish-assembly-shortreads/chr_names.txt

SHORT_READS_BAM: /lustre/nobackup/WUR/ABGC/moiti001/mapping_all_short/sorted_reads/DTG-SG-188.sort.bam 

# set directory were snakemake will run and results will be saved
OUTDIR: /lustre/nobackup/WUR/ABGC/moiti001/polish_secondround
