# Reference
#assembly: /lustre/backup/WUR/ABGC/shared/ABGC_Projects/Turkey_Assembly/HiC_assembly/Mgal6.fa

# Polished assembly - used for second round of polishing
assembly: /lustre/nobackup/WUR/ABGC/moiti001/results/polished_assembly/results/pilon.fasta

# BAM from aligning to polished assembly - used for second round of polishing
BAM: /lustre/nobackup/WUR/ABGC/moiti001/results/map_SG_polished_assembly/sorted_reads/DTG-SG-188.sort.bam

# for first round of polishing
# BAM: /lustre/nobackup/WUR/ABGC/moiti001/mapping_all_short/sorted_reads/DTG-SG-188.sort.bam 


# set directory were snakemake will run and results will be saved
OUTDIR: /lustre/nobackup/WUR/ABGC/moiti001/polish_secondround

nregions: 244