# Reference
assembly: HiC_assembly/Mgal6.fa

# Directory with data to use (for reads and reference)
DATADIR: /lustre/backup/WUR/ABGC/shared/ABGC_Projects/Turkey_Assembly/

BAM: realign_pacbio/pb_mapped_Mgal6.sorted.bam

# file with regions to use for variant calling:
# can be created from the BAM file:
    # module load samtools && samtools idxstats <BAM> | cut -f 1 > chr_names.txt
REGIONS: chr_names.txt

# set directory were snakemake will run and results will be saved
# OUTDIR: /lustre/nobackup/WUR/ABGC/moiti001/polish-assembly-shortreads